### PR TITLE
Add subscription item ID

### PR DESCRIPTION
**Pull request by LewisDavies**
Pull Request
**Are you a current Fivetran customer?** 
Lewis Davies, Senior Analytics Engineer, Prisma

**What change(s) does this PR introduce?** 
Adds `subscription_item_id` column to `stripe__invoice_line_items`, allowing the model to be joined to [Stripe Usage Records](https://stripe.com/docs/api/usage_records).

**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)
It simply brings through a column that already exists in an upstream model.

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [x] Local (please provide additional testing details below)
I made the changes on my machine and installed the local version in my dbt project by adding `- local: ~/dbt_stripe` to `packages.yml`. I then successfully ran `dbt build -s package:stripe`.

**Select which warehouse(s) were used to test the PR**
 

- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Hi @LewisDavies thanks for opening this PR! 

I believe the addition of the `subscription_item_id` to the `stripe__invoice_line_item` table makes sense to me and could be leveraged by others. In addition to your updates already in the PR, would you be able to include this field in the `stripe.yml` documentation for this model?

Once you apply that update, I believe this may look good to move forward!

**Comment by LewisDavies** [comment]
FYI @fivetran-joemarkiewicz Docs have been updated now

**Review by fivetran-joemarkiewicz — APPROVED** [review]
Thanks so much for opening this PR @LewisDavies! The updates you made on your end look great and are ready to be integrated into the package.

I have changed the base branch to be a staging branch before merging to `main`. There are a few other behind the scenes testing updates that will need to go into the updates before merging them to main. I will be sure to clue you in once that new branch is merged and the release is cut!

**Comment by fivetran-joemarkiewicz** [comment]
@LewisDavies we will most likely be cutting a new release come Monday. I hope to get it out sooner, but we prefer to not cut releases on Friday's. You can follow the PR #52 for status on the merge and release of your changes to the package!

**Pull request merged**
